Blog/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path,include
from Blog import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^$',views.login_redirect,name='login_redirect'),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^admin/', admin.site.urls),
    url(r'^home/',include('home.urls',namespace='home')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
    login,logout,password_reset,password_reset_done,password_reset_confirm,password_reset_complete
)
app_name='accounts'
urlpatterns=[
     url(r'^regeister/$',views.regeister,name='regeister'),
     url(r'^login/$',login,{'template_name':'accounts/login.html'},name='login'),
     url(r'^logout/$',logout,{'template_name':'accounts/logout.html'},name='logout'),
     url(r'^profile/$',views.view_profile,name='view_profile'),
     url(r'^profile/(?P<pk>\d+)/$',views.view_profile,name='view_profile_with_pk'),
     url(r'^profile/edit/$',views.edit_profile,name='edit_profile'),
     url(r'^change-password/$',views.change_password,name='change_password'),
    url(r'^reset-password/$', password_reset,{'template_name':'accounts/reset_password.html'}, name='reset_password'),
    url(r'^reset-password/done/$', password_reset_done,{'template_name':'accounts/reset_password_done.html'},
        name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,
        {'template_name':'accounts/password_reset_confirm.html'},name='password_reset_confirm'),
    url(r'^reset-password/complete/$', password_reset_complete,
        {'template_name':'accounts/password_reset_complete.html'},name='password_reset_complete'),


]

home/urls.py
from django.conf.urls import url
from home.views import HomeView
from .import views
app_name='home'
urlpatterns=[
    url(r'^$',HomeView.as_view(),name='home'),
    url(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$',views.change_friend,name='change_friend'),

]

home/models.py
from django.db import models
from django.contrib.auth.models import User
class Post(models.Model):
    post=models.CharField(max_length=500)
    user=models.ForeignKey(User,on_delete='cascade')
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
class Friend(models.Model):
    users=models.ManyToManyField(User)
    current_user=models.ForeignKey(User,on_delete='cascade',related_name='owner',null=True)
    @classmethod
    def make_friend(cls,current_user,new_friend):
        friend,created=cls.objects.get_or_create(
            current_user=current_user
        )
        friend.users.add(current_user,new_friend)
    @classmethod
    def lose_friend(cls,current_user,new_friend):
        friend,created=cls.objects.get_or_create(
            current_user=current_user
        )
        friend.users.remove(current_user,new_friend)

home/forms.py
from django import forms
from home.models import Post
class HomeForm(forms.ModelForm):
    post=forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'form-control',
            'placeholder':'Write a Post........'

        }
    ))
    class Meta:
        model=Post
        fields=('post',)

home/views.py
from django.views.generic import TemplateView
from django.shortcuts import render,redirect
from home.forms import HomeForm
from home.models import Post,Friend
from django.contrib.auth.models import User
class HomeView(TemplateView):
    template_name='home/home.html'
    def get(self,request):
        form=HomeForm()
        posts=Post.objects.all().order_by('-created')
        users=User.objects.exclude(id=request.user.id)
        friend,created=Friend.objects.get_or_create(current_user=request.user)
        friends=friend.users.all()
        args={'form':form,'posts':posts,'users':users,'friends':friends}
        return render(request,self.template_name,args)
    def post(self,request):
        form=HomeForm(request.POST)
        post=form.save(commit=False)
        post.user=request.user
        post.save()
        if form.is_valid():
            text=form.cleaned_data['post']
            form=HomeForm()
            return redirect('home:home')
        args={'form':form,'text':text}
        return render(request,self.template_name,args)
def change_friend(request,operation,pk):
    friend=User.objects.get(pk=pk)
    if operation=='add':
        Friend.make_friend(request.user,friend)
    elif operation=='remove':
        Friend.lose_friend(request.user,friend)
    return redirect('home:home')

home/templates/home/home.html
{% extends "accounts/base.html" %}
{% block body %}
    <div class="container">
        <div class="col-md-9">
        <form method="post">
        {% csrf_token %}
        {{form.post}}
        <br>
        <button type="submit">Post</button>
        </form>
        {% for post in posts %}
          <h3 style="color:black;">{{ post.post }}</h3>
          <p style="color:green;">Posted by {{post.user.get_full_name}} on {{ post.created }}</p>
          
        {% endfor %}
      </div>
      <div class="col-md-3">
          <h1>Other People</h1>
          {% for user in users %}
           <a href="{% url 'accounts:view_profile_with_pk' pk=user.pk %}">
                <h3>{{user.username}}</h3>
           </a>
           {% if not user in friends %}
           <a href="{% url 'home:change_friend' operation='add' pk=user.pk %}">
                <button type="button" class="btn btn-success">Add Friend</button>
          </a>
          {% endif %}
          {% endfor %}
          <h1>Friends</h1>
          {% for friend in friends %}
           <a href="{% url 'accounts:view_profile_with_pk' pk=user.pk %}">
                <h3>{{friend.username}}</h3>

           </a>
           <a href="{% url 'home:change_friend' operation='remove' pk=friend.pk %}">
           <button type="button" class="btn btn-secondary">Unfriend</button>
           </a>
          {% endfor %}
      </div>
    </div>
{% endblock   %}