Blog/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path,include
from Blog import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^$',views.login_redirect,name='login_redirect'),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^admin/', admin.site.urls),
    url(r'^home/',include('home.urls',namespace='home')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
    login,logout,password_reset,password_reset_done,password_reset_confirm,password_reset_complete
)
app_name='accounts'
urlpatterns=[
     url(r'^regeister/$',views.regeister,name='regeister'),
     url(r'^login/$',login,{'template_name':'accounts/login.html'},name='login'),
     url(r'^logout/$',logout,{'template_name':'accounts/logout.html'},name='logout'),
     url(r'^profile/$',views.view_profile,name='view_profile'),
     url(r'^profile/(?P<pk>\d+)/$',views.view_profile,name='view_profile_with_pk'),
     url(r'^profile/edit/$',views.edit_profile,name='edit_profile'),
     url(r'^change-password/$',views.change_password,name='change_password'),
    url(r'^reset-password/$', password_reset,{'template_name':'accounts/reset_password.html'}, name='reset_password'),
    url(r'^reset-password/done/$', password_reset_done,{'template_name':'accounts/reset_password_done.html'},
        name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,
        {'template_name':'accounts/password_reset_confirm.html'},name='password_reset_confirm'),
    url(r'^reset-password/complete/$', password_reset_complete,
        {'template_name':'accounts/password_reset_complete.html'},name='password_reset_complete'),


]

home/urls.py
from django.conf.urls import url
from home.views import HomeView
from .import views
app_name='home'
urlpatterns=[
    url(r'^$',HomeView.as_view(),name='home'),
    url(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$',views.change_friend,name='change_friend'),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
# Create your models here.

class UserProfileManager(models.Manager):
    pass
class UserProfile(models.Model):
    user=models.OneToOneField(User,on_delete='CASCADE')
    description=models.CharField(max_length=100,default='')
    city=models.CharField(max_length=100,default='')
    website=models.URLField(default='')
    phoneno=models.IntegerField(default=0)
    image=models.ImageField(upload_to='profile_image',blank=True)
    def __str__(self):
        return self.user.username

def create_profile(sender,**kwargs):
    if kwargs['created']:
        userprofile=UserProfile.objects.create(user=kwargs['instance'])
    

post_save.connect(create_profile,sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from accounts.models import UserProfile



class RegeistrationForm(UserCreationForm):
    email=forms.EmailField(required=True)
    class Meta:
        model=User
        fields=(
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'

        )
    def save(self,commit=True):
        user=super(RegeistrationForm,self).save(commit=False)
        user.first_name=self.cleaned_data['first_name']
        user.last_name=self.cleaned_data['last_name']
        user.email=self.cleaned_data['email']

        if commit:
            user.save()
        return user
class EditProfileForm(UserChangeForm):
    email=forms.EmailField(required=False)
    class Meta:
        model=UserProfile
        fields=(
            'email',
            'description',
            'city',
            'website',
            'phoneno',
            'password',
        )
    def save(self,commit=True):
        user=super(EditProfileForm,self).save(commit=False)
        userprofile=user.userprofile
        userprofile.description=self.cleaned_data['description']
        userprofile.city=self.cleaned_data['city']
        userprofile.website=self.cleaned_data['website']
        userprofile.phoneno=self.cleaned_data['phoneno']
        user.email=self.cleaned_data['email']
        if commit:
            userprofile.save()
            user.save()
        return user

accounts/views.py
from django.shortcuts import render,HttpResponse,redirect
from accounts.forms import RegeistrationForm,EditProfileForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm,PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
# Create your views here.


def regeister(request):
    if request.method=='POST':
        form=RegeistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/home')
    else:
        form=RegeistrationForm()
    args={'form':form}
    return render(request,'accounts/reg_form.html',args)


def view_profile(request,pk=None):
    if pk:
        user=User.objects.get(pk=pk)
    else:
        user=request.user
    args={'user':user}
    return render(request,'accounts/profile.html',args)


def edit_profile(request):
    if request.method== 'POST':
        form=EditProfileForm(request.POST,instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('/accounts/profile')
    else:
        form=EditProfileForm(instance=request.user)
        args={'form':form}
        return render(request,'accounts/edit_profile.html',args)

def change_password(request):
    if request.method== 'POST':
        form=PasswordChangeForm(data=request.POST,user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request,form.user)
            return redirect('/accounts/profile')
        #else:
         #   return redirect('/accounts/change_password')
    else:
        form=PasswordChangeForm(user=request.user)
    args={'form':form}
    return render(request,'accounts/change_password.html',args)



    
        
    

accounts/templates/accounts/base.html
<html>
        <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
            <meta name="viewport" content="width=device-width",initial-scale="1.0">
            {% block head %}     
            {% endblock  %}
        </head>
        <body>
                <div class="container-fluid">
                <nav class="navbar navbar-default">
                        <div class="container-fluid">
                          <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                              <span class="sr-only">Toggle navigation</span>
                              <span class="icon-bar"></span>
                              <span class="icon-bar"></span>
                              <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand" href="{% url 'home:home' %}">Tweepy</a>
                          </div>
                          <div id="navbar" class="navbar-collapse collapse">
                            {% if user.is_authenticated %}
                            <ul class="nav navbar-nav">
                                <li><a href="{% url 'home:home' %}">Home</a></li>
                                <li><a href="{% url 'accounts:view_profile' %}">Profile</a></li>
                                <li><a href="{% url 'accounts:edit_profile' %}">Edit Profile</a></li>
                                <li><a href="{% url 'accounts:change_password' %}">Change Password</a></li>
                                
                            </ul>
                            <ul class="nav navbar-nav navbar-right">
                                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                            </ul>
                            {% else %}
                            <ul class="nav navbar-nav">
                                <li><a href="{% url 'accounts:reset_password' %}">Reset Password</a></li>
                            </ul>
                            <ul class="nav navbar-nav navbar-right">
                                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                              <li><a href="{% url 'accounts:regeister' %}">Regeister</a></li>
                            </ul>
                            {% endif %}
                         </div>
                        </div>
                </nav>
            </div>
                {% block body %}

                {% endblock %}
        </body>
    </html>

accounts/templates/accounts/change_password.html
{% extends 'accounts/base.html' %}
{% block body %}
       <div class="container">
       <h3>EditProfile</h3>
       <form method="POST">
           {% csrf_token %}
           {{ form.as_p }}
           <button type="submit">Submit</button>
       </form>
    </div>
{% endblock  %}

accounts/templates/accounts/edit_profile.html
{% extends 'accounts/base.html' %}
{% block body %}
       <div class="container">
       <h3>EditProfile</h3>
       <form method="POST">
           {% csrf_token %}
           {{ form.as_p }}
           <button type="submit">Submit</button>
       </form>
    </div>
{% endblock  %}

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% block body %}
       <div class="container">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Login</button>
            </form>
    </div>
{% endblock  %}

accounts/templates/accounts/logout.html
{% extends 'accounts/base.html' %}
{% block body %}
       <div class="container">
            <h1 >You are successfully logged out</h1>
       </div>
{% endblock  %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'accounts/base.html' %}
{% block body %}
       <div class="container" style="color:green;">
           <p>Password Changed Successfully</p>
           <a href='{% url 'login' %}'>login</a>
    </div>
{% endblock  %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'accounts/base.html' %}
{% block body %}
       <div class="container">
           <h3>Enter New Password</h3>
       <form method="POST">
           {% csrf_token %}
           {{ form.as_p }}
           <button type="submit">Reset Password</button>
       </form>
    </div>
{% endblock  %}

accounts/templates/accounts/profile.html
{% extends 'accounts/base.html' %}
{% block head %}
     <title>Profile</title>
{% endblock %}
{% block body %}
  <div class="container">
      <h1>Profile</h1>
      <p>Firstname:{{user.first_name}}</p>
      <p>Lastname:{{user.last_name}}</p>
      <p>email:{{user.email}}</p>
      <p>Description:{{user.userprofile.description}}</p>
      <p>city:{{user.userprofile.city}}</p>
      <p>website:{{user.userprofile.website}}</p>
      <p>phoneno:{{user.userprofile.phoneno}}</p>
      {% if user.userprofile.image %}
      <img src="{{ user.userprofile.image.url }}" width="240">
      {% endif %}
      


  </div>
{% endblock %}

accounts/templates/accounts/reg_form.html
{% extends 'accounts/base.html' %}
{% block body  %}
   <div class="container"">
   <form method="POST">
       {% csrf_token %}
       {{ form.as_p }}
      <button type="submit">Regeister</button>
   </form>
   </div>
{% endblock  %}}

accounts/templates/accounts/reset_password.html
{% extends 'accounts/base.html' %}
{% block body %}
       <div class="container">
           <h3>Reset Password</h3>
       <form method="POST">
           {% csrf_token %}
           {{ form.as_p }}
           <button type="submit">Reset</button>
       </form>
    </div>
{% endblock  %}

accounts/templates/accounts/reset_password_done.html
{% extends 'accounts/base.html' %}
{% block body %}
       <div class="container" style="color:green;">
           <p>Link send to your email address to reset password</p>
    </div>
{% endblock  %}